version: "3.7"
services:
  flask:
    build: ./backend
    container_name: "primary-backup-container"
    restart: always
    environment:
      - APP_NAME=PrimaryBackup
    expose:
      - 8080
  nginx:
    build: ./nginx
    container_name: "nginx"
    restart: always
    ports:
      - "5000:80"
